name: 'NPM install'
description: 'Run npm install with cache enabled'

runs:
  using: 'composite'

  steps:
    - name: install node v18
      uses: actions/setup-node@main
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: ./package.json  
    - name: cache node-modules
      id: cache
      uses: actions/cache@main
      with:
        path: ${{ github.workspace }}/node_modules
        key: modules-${{ hashFiles('./package.json') }}
    - name: install packages        
      working-directory: ${{ github.workspace }}
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci --include=dev