# Workflow for build, Test, lint and geerneate reports in separate steps
name: "ReFlex: Build, Test Library and Tools"

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # build library, generate test report and upload as artifact
  generate_test-report_library:
    uses: ./.github/workflows/library-test.yml
  # build server, generate test report and upload as artifact
  build_server:
    uses: ./.github/workflows/server-build.yml
  lint_server:
    uses: ./.github/workflows/server-lint.yml
  # build server, generate test report and upload as artifact
  generate_test-report_server:
    uses: ./.github/workflows/server-test.yml
  build_emulator:
      uses: ./.github/workflows/emulator-build.yml
