# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: "ReFlex: Build, Test Library and Tools"

on:  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # caches are scoped to branches and keys !
  # however, cache for main branch can be accessed by other branches --> therefore, pushes on main should always trigger this workflow
  push:
    branches:
      - main
  # run when main branch is updated and on pull requests
  # as result, child workflows are not triggered anymore on prs
  pull_request: 
    types: [ opened, reopened, edited, synchronize ]
    branches:
      - main

jobs:
  # build library, generate test report and upload as artifact
  generate_test-report_library:
    uses: ./.github/workflows/library-test.yml  
  # build server, generate test report and upload as artifact
  build_server:
    uses: ./.github/workflows/server-build.yml
  lint_server:
    uses: ./.github/workflows/server-lint.yml  
  # build server, generate test report and upload as artifact
  generate_test-report_server:
    uses: ./.github/workflows/server-test.yml
  build_emulator:
      uses: ./.github/workflows/emulator-build.yml