name: "ReFlex Emulator: Build"

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened, edited, synchronize ]
    branches:
      - main
jobs:
  build-emulator:
    runs-on: windows-latest
    name: install and build
    steps:
      - name: checkout repo with submodules
        uses: actions/checkout@main
      - name: install node v18
        uses: actions/setup-node@main
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ./package.json
      - name: cache node-modules
        id: cache
        uses: actions/cache@main
        with:
          path: ${{ github.workspace }}/node_modules
          key: modules-${{ hashFiles('./package.json') }}
      - name: cache node-modules emulator
        id: cache_emulator
        uses: actions/cache@main
        with:
          path: ${{ github.workspace }}/tools/emulator/node_modules
          key: modules-${{ hashFiles('./tools/emulator/package.json') }}
      - name: install packages
        working-directory: ${{ github.workspace }}
        if: steps.cache.outputs.cache-hit != 'true' || steps.cache_emulator.outputs.cache-hit != 'true'
        run: npm ci --include=dev
      - name: build shared types
        run: npm run build:shared-types
      - name: build angular components
        run: npm run build:shared-components
      - name: build emulator
        run: npm run build:emulator
