name: "ReFlex: Build/Lint/Test all npm projects"

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened, edited, synchronize ]
    branches:
      - main

jobs:
  angular-lint:
    runs-on: windows-latest
    name: install and build
    steps:
      - name: checkout repo with submodules
        uses: actions/checkout@main
      - name: install node v18
        uses: actions/setup-node@main
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ./package.json
      - name: cache node-modules
        id: cache
        uses: actions/cache@main
        with:
          path: ${{ github.workspace }}/node_modules
          key: modules-${{ hashFiles('./package.json') }}
      - name: install packages
        working-directory: ${{ github.workspace }}
        # install even when cache hit - update npm packages in workspaces
        run: npm ci --include=dev
      - name: build complete (build / lint / test-ci commands in each workspace)
        run: npm run build-complete
