name: "ReFlex Server: Lint"

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened, edited, synchronize ]
    branches:
      - main

jobs:
  angular-lint:
    runs-on: windows-latest
    name: install and lint
    steps:
      - name: checkout repo with submodules
        uses: actions/checkout@main
      - name: install node v18
        uses: actions/setup-node@main
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ./package.json
      - name: cache node-modules
        id: cache
        uses: actions/cache@main
        with:
          path: ${{ github.workspace }}/node_modules
          key: modules-${{ hashFiles('./package.json') }}
      - name: install packages
        working-directory: ${{ github.workspace }}
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --include=dev
      - name: build shared types
        run: npm run build:shared-types
      - name: build angular components
        run: npm run build:shared-components
      - name: run linter
        working-directory: ${{ github.workspace }}
        run: npm run lint:server
