name: "ReFlex Server: Test"

on: 
  # make this workflow reusable
  workflow_call:
    outputs:
      artifact_name:
        description: "name of the artifact that has been uploaded"
        value: ${{ jobs.test-server.outputs.artifact_name }}
  # this workflow can be triggered manually
  workflow_dispatch:
  
jobs:
  test-server: 
    runs-on: windows-latest
    name: install and test
    env:
      artifact_name: Angular Test Report (ReFlex TrackingServer)
    outputs:
      artifact_name: ${{ env.artifact_name }}
    steps:
      - name: checkout repo with submodules
        uses: actions/checkout@main
      - name: install node v18
        uses: actions/setup-node@main
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ./package.json  
      - name: cache node-modules
        id: cache
        uses: actions/cache@main
        with:
          path: ${{ github.workspace }}/node_modules
          key: modules-${{ hashFiles('./package.json') }}
      - name: install packages        
        working-directory: ${{ github.workspace }}
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --include=dev
      - name: build shared types
        run: npm run build:shared-types 
      - name: run test
        working-directory: ${{ github.workspace }}
        run: npm run test:server
      - name: Attach TestResults as Build Artifact
        uses: actions/upload-artifact@main
        with:
          name: ${{ env.artifact_name }}
          path: ${{ github.workspace }}/test/artifacts/coverage 
      - name: Publish JUnit Test Report
        uses: mikepenz/action-junit-report@main
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '${{ github.workspace }}/test/artifacts/tests/junit-test-results.xml'
      
        
