name: "ReFlex Shared Types: Build"

on: 
  # make this workflow reusable
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened, edited, synchronize ]
    branches:
      - main

jobs:
  build-shared-types:
    runs-on: windows-latest
    name: build shared ts types
    steps:
      - name: checkout repo with submodules
        uses: actions/checkout@main
      - name: install node v18
        uses: actions/setup-node@main
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ./package.json  
      - name: cache node-modules
        id: cache
        uses: actions/cache@main
        with:
          path: ${{ github.workspace }}/node_modules
          key: modules-${{ hashFiles('./package.json') }}
      - name: install packages        
        working-directory: ${{ github.workspace }}
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --include=dev
      - name: build shared types
        run: npm run build:shared-types 
